import {GraphQLLiveDirective} from "@n1ru4l/graphql-live-query";
import {printSchema, specifiedDirectives} from "graphql";
import {writeFileSync} from "node:fs";
import {join} from "node:path";
import {builder} from "./builder";
import "./resolvers";

export const schema = builder.toSchema({
  directives: [...specifiedDirectives, GraphQLLiveDirective],
});

if (process.env.NODE_ENV !== "production") {
  const schemaAsString = printSchema(schema);
  writeFileSync(
    join(process.cwd(), "src/autogenerated/schema.gql"),
    schemaAsString
  );
}
